name: angel_firestore
description: >-
  Admin Firebase firestore service for the angel framework.
  With this package you can use firestore as a DB in your angel project.
version: 0.1.3
homepage: https://github.com/netantho/angel_firestore
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angel_framework: ^2.1.1
  dartbase_admin: ^0.1.3
  http: ^0.12.1
dev_dependencies:
  angel_container: ^1.1.0
  dotenv: ^2.0.0
  json_god: ">=2.0.0-beta <3.0.0"
  test: ^1.15.1
  pedantic: ^1.9.0
